### ISSUE TITLE
大神怎么启用分类,我的PC端无法启用目录

### ISSUE THREAD

**Issue by wenhainan** [AlanDecode/Typecho-Theme-VOID#1]
超级喜欢大佬的主题,希望指点迷津

**Comment by AlanDecode** [comment]
如果你说的是归档页面，目前你已经启用了。如果你说的是单独的分类页面，PC 端目前没有添加入口，但后续可能会在顶部导航栏添加。

另外你一直都可以通过形如 https://blog.imalan.cn/category/tech/ 这样的链接访问某一分类下的文章。

**Comment by wenhainan** [comment]
> 如果你说的是归档页面，目前你已经启用了。如果你说的是单独的分类页面，PC 端目前没有添加入口，但后续可能会在顶部导航栏添加。
> 
> 另外你一直都可以通过形如 https://blog.imalan.cn/category/tech/ 这样的链接访问某一分类下的文章。

好的,我自己加上分类
