### ISSUE TITLE
您好，我想修改下代码高亮部分应该改哪个文件啊

### ISSUE THREAD

**Issue by uu0** [AlanDecode/Typecho-Theme-VOID#10]
代码高亮支持的语言有限，不太适合我。想自定义一下。看了下项目好像是用 `hightlight.js`.实现的，但是找了文件里并没有这个 `JS` 文件。不知道该如何改起，诸位可以指点一下吗？
顺便，强力安利一波  [Prism.js ](https://prismjs.com/ ) 可以自定义支持的语言，插件（代码复制，行号，高亮之类的）。二次开发超级方便。希望作者大大能爱上它。

**Comment by AlanDecode** [comment]
Highlight.js 相关文件位于 `assets/libs/hljs` 文件夹下，如果需要自行更改，请参照 README.md 中 https://github.com/AlanDecode/Typecho-Theme-VOID#%E5%BC%80%E5%8F%91 相关内容。

**Comment by uu0** [comment]
谢谢。
