### ISSUE TITLE
诸位有遇到过友链乱码的问题吗？

### ISSUE THREAD

**Issue by uu0** [AlanDecode/Typecho-Theme-VOID#11]
# 我是这么做的。
## 1，新建独立页面。
![image](https://user-images.githubusercontent.com/33198600/55672546-c863c600-58ce-11e9-892f-c067770b1396.png)

## 2，在独立页面，直接复制粘贴示例代码。
![image](https://user-images.githubusercontent.com/33198600/55672550-d0236a80-58ce-11e9-9791-ef57cc643970.png)

## 3，发布以后就变成这样子了。
![image](https://user-images.githubusercontent.com/33198600/55672529-a1a58f80-58ce-11e9-811a-a42aff0fa442.png)

求教大概可能是哪方面的问题，用的是最新的开发版。

**Comment by valext** [comment]
经过我的测试，需要在前面和后面同时加上！！！即可解决。
环境 :php 版本7.2 使用发布版

**Comment by uu0** [comment]
@valext PHP 用的5.6. 应该在哪个位置加呢？
!!![link] 
...
[/links]!!!
这样子吗？

**Comment by valext** [comment]
是的

**Comment by uu0** [comment]
试了下 不工作

**Comment by AlanDecode** [comment]
!!! 需要单独占一行

**Comment by uu0** [comment]
按照如下格式解决了问题。谢谢楼上诸位
```
!!!
[link]
.... ...

[/links]
!!!
```
