### ISSUE TITLE
主题相关

### ISSUE THREAD

**Issue by valext** [AlanDecode/Typecho-Theme-VOID#12]
作者你好，我想请问网站的logo如何添加？同时作者可以增加登陆界面吗？

**Comment by AlanDecode** [comment]
高级设置中 `name` 字段可以自定义左上角显示的内容，符合要求的呃 HTML 也是可以的。
登陆界面是指？为了不暴露后台地址，我不会在前台添加登陆界面链接。

**Comment by valext** [comment]
你好，我想了解的是
![image](https://user-images.githubusercontent.com/33391923/55681846-c5fc7d00-595d-11e9-9737-d8321011263c.png)这个logo如何添加，多谢告知。

**Comment by AlanDecode** [comment]
制作 favicon.ico 并放在站点根目录下，大多数浏览器会自己抓取。也有帮助你生成全套 icon 的网站：https://realfavicongenerator.net/，请自行了解。

**Comment by valext** [comment]
多谢了
