### ISSUE TITLE
感谢楼主制作这个主题，请问能否增加一个Tags标签云的模板页面？

### ISSUE THREAD

**Issue by goxofy** [AlanDecode/Typecho-Theme-VOID#13]
另外请教一下楼主，”首页顶部大图内文字“如何设置两行文字呢？

**Comment by goxofy** [comment]
另外报个一个Bug，如果博客文章通篇全部为英文的话，字数统计会显示0个字

**Comment by AlanDecode** [comment]
1. 关于设置两行文字，你可以通过填写HTML完成，例如我的博客是这样写的：

```html
<span class="brand">无文字 | 三无计划</span><span style="font-size:1.2rem;display: block;margin-top: 1rem; ">  2019, I AM STILL ALAN. </span>
```

2. 关于字数统计，目前是统计中文字数，后续也许会优化。
3. Google Font 我实测结果是够用的，在国内也有 CDN 节点，考虑到可靠性，也许不会更换。你可以自行更换，因为只有一行代码而已。

**Comment by goxofy** [comment]
1和3已经解决了，把Google Font缓存到本地了。

第二个字数统计是在哪改呢？

**Comment by goxofy** [comment]
均已解决，感谢
