### ISSUE TITLE
请教一个问题，如何正确的关闭service worker？

### ISSUE THREAD

**Issue by goxofy** [AlanDecode/Typecho-Theme-VOID#14]
我在后台关闭service worker之后，客户端仍然缓存着旧的静态文件，无法更新。求救

**Comment by AlanDecode** [comment]
浏览器 f12，Application 选项卡下有 Service Workers 页，找到对应的点击 Unregister 就行。然后 ctrl+f5 刷新。
静态文件建议通过文件名控制版本，防止缓存旧版本。

**Comment by goxofy** [comment]
其他访问者如果不知道通过F12 Unregister对应的 Service Workers的话，是不是只能通过静态文件改名来更新版本了？

**Comment by AlanDecode** [comment]
是，除非缓存自己过期。

**Comment by goxofy** [comment]
能否考虑在service worker功能上实现unregister？

**Comment by AlanDecode** [comment]
暂不考虑实现。

**Comment by AlanDecode** [comment]
已在开发版中实现。

**Comment by goxofy** [comment]
感谢

**Comment by goxofy** [comment]
@AlanDecode 你好，再请教一个问题，因为我这边引用了第三方得评论系统，所以内容页面banner里面的评论统计需要改一下，但是我这边不知道什么情况，无论怎么改动都不起作用，准确的说是banner里面的任何内容我修改之后都没有任何反应。

但是我把我自己的评论统计代码加到 postCheck 段上面里面都可以正常工作，唯独就是banner里不生效，还请指点。

**Comment by goxofy** [comment]
@AlanDecode 求助大佬解决下
