### ISSUE TITLE
关于修改内容页banner不生效的问题

### ISSUE THREAD

**Issue by goxofy** [AlanDecode/Typecho-Theme-VOID#15]
你好，再请教一个问题，因为我这边引用了第三方的评论系统，所以内容页面banner里面的评论统计需要改一下，但是我这边不知道什么情况，无论怎么改动都不起作用，准确的说是banner里面的任何内容（例如author、time、comments等）我修改之后都没有任何反应。

但是我把我自己的评论统计代码加到 postCheck 段里是可以正常工作的，唯独就是banner里不生效，还请指点。

**Comment by AlanDecode** [comment]
那就不要改。

**Comment by goxofy** [comment]
改好了，呵呵
