### ISSUE TITLE
字数统计有问题，很多文章统计为0

### ISSUE THREAD

**Issue by cyea** [AlanDecode/Typecho-Theme-VOID#17]
![image](https://user-images.githubusercontent.com/22478003/60168861-2ce05280-9838-11e9-8198-f9ad598bbead.png)

**Comment by AlanDecode** [comment]
先重启一下 VOID 插件试试？如果还是不行请提供页面链接、Typecho 版本、PHP 版本、数据库类型。

**Comment by cyea** [comment]
重启了一下 OK了
