### ISSUE TITLE
归档页面有一个"接收邮件通知"的按钮

### ISSUE THREAD

**Issue by waleslau** [AlanDecode/Typecho-Theme-VOID#18]
归档页面底部"感谢陪伴"上面有一个"接收邮件通知"的可勾选按钮,不知道是做什么用的，是BUG吗？[点击查看](https://blog.mind-echo.xyz/archives.html)

**Comment by AlanDecode** [comment]
似乎没有发现这个问题啊？请问你用的是哪个版本？

**Comment by waleslau** [comment]
昨天之前我用的是发布版，刚才我换成开发板主题就没有那个东西了~~~

**Comment by waleslau** [comment]
> 似乎没有发现这个问题啊？请问你用的是哪个版本？

昨天之前我用的是发布版，刚才我换成开发板主题就没有那个东西了~~~

**Comment by waleslau** [comment]
> 似乎没有发现这个问题啊？请问你用的是哪个版本？

刚换了10分钟不到，好巧。。。

**Comment by AlanDecode** [comment]
可能是上次调整结构时引入的问题，不过现在没问题就行了
