### ISSUE TITLE
选中文字背景颜色 与 日间/夜间模式

### ISSUE THREAD

**Issue by festoney8** [AlanDecode/Typecho-Theme-VOID#19]
目前选中文字的样式是 文字白色，背景黄色高亮
```
::selection {
    color: #fff;
    background-color: #ffe150;
}
```
在夜间模式下选中文字的可见度尚可，但日间模式下选中文字看不清，难以阅读

希望能提高两种模式下选中文字的可读性，分离日间和夜间模式的选中文字样式，如日间使用深灰高亮
或加入advance settings让用户自定义两种模式的高亮色

**Comment by AlanDecode** [comment]
会考虑的，感谢建议。
