### ISSUE TITLE
代码块显示不全问题

### ISSUE THREAD

**Issue by halfye** [AlanDecode/Typecho-Theme-VOID#20]
在Android手机的微信、chrome浏览器上超过59（也可能是61）行代码会被蒙上，图为微信和chrome浏览器，在火狐浏览器正常显示。
![Screenshot_2019-07-25-21-00-59-485_com tencent mm](https://user-images.githubusercontent.com/30193214/61876664-fcb3ce80-af1f-11e9-8b7f-527a0a66a49f.png)
![Screenshot_2019-07-25-21-01-29-655_com chrome bet](https://user-images.githubusercontent.com/30193214/61876674-01788280-af20-11e9-9abe-1ae620ddb52b.png)

**Comment by qfmx** [comment]
我的也有这个问题

**Comment by qfmx** [comment]
2.2.1没有问题

**Comment by AlanDecode** [comment]
手里没有安卓设备，模拟器和 iOS 上始终没有复现，请提供复现步骤以及有问题的页面链接。

**Comment by halfye** [comment]
模拟器可以采用夜神模拟器，通过设置为手机模式 重启生效后通过自带的浏览器浏览https://www.ccode.fun/c/wyshszejz.html就可以发现问题。
[夜神模拟器切换为手机模式操作：如链接中的图片](https://files.ccode.fun/bug.png)

（这个问题出现在竖屏上，横屏显示正常，且字体越小显示行数越高）

**Comment by qfmx** [comment]
该如何解决？问题确实是竖屏


 
---原始邮件---
发件人: "halfye"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 下午4:31
收件人: "AlanDecode/Typecho-Theme-VOID"<Typecho-Theme-VOID@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"allms"<1125438556@qq.com>;
主题: Re: [AlanDecode/Typecho-Theme-VOID] 代码块显示不全问题 (#20)



模拟器可以采用夜神模拟器，通过设置为手机模式 重启生效后通过自带的浏览器浏览https://www.ccode.fun/c/wyshszejz.html就可以发现问题。
 夜神模拟器切换为手机模式操作：如链接中的图片
 
（这个问题出现在竖屏上，横屏显示正常，且字体越小显示行数越高）

**Comment by AlanDecode** [comment]
这个问题看上去是浏览器的问题，暂时没找到好的解决方案
