### ISSUE TITLE
启用1.1版本插件时报错

### ISSUE THREAD

**Issue by ybw2016v** [AlanDecode/Typecho-Theme-VOID#23]
升级3.3版本时安装插件出错，原版1.01插件已经彻底删除
随主题发布的插件和开发版插件全都试过，同样报错
数据库用的是sqlite
SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error

**Comment by AlanDecode** [comment]
SQLite 有些功能不支持，所以会有问题，这是已知的。
