### ISSUE TITLE
改变代码块样式

### ISSUE THREAD

**Issue by rainfor3st** [AlanDecode/Typecho-Theme-VOID#24]
您好，我注意到 latest release 已经把代码高亮换成了 Prism.js，能知道下如何替换成自己想要的风格吗？谢谢努力。

**Comment by rainfor3st** [comment]
bundle-039f6998e4.js
VOID-41ba0494ad.css

貌似 Prism.js  的 js 和 css 文件被放在了上面的两个文件里面？

**Comment by AlanDecode** [comment]
Prism 相关文件都被打包进了主题文件中，直接修改不太容易。
你可以下载源码，修改后打包。

**Comment by rainfor3st** [comment]
明白，谢谢。

**Comment by rainfor3st** [comment]
想说希望作者可以考虑把一些可以个性化配置的文件开放出来，方便用户配置，成本也不会很高。谢谢啦。
