### ISSUE TITLE
文章头图跟首页头图是否可以分离

### ISSUE THREAD

**Issue by luhe0625** [AlanDecode/Typecho-Theme-VOID#26]
默认是同步的，但是其实首页的图不需要过高的分辨率，可以请求图床一个低分的图片，类似路过图床是在链接中增加 .md 实现，如：
原始图片：https://s2.ax1x.com/2019/10/23/KtM5WR.jpg
中等大小：https://s2.ax1x.com/2019/10/23/KtM5WR.md.jpg
如果分离了必然会增加复杂度，增加一个图片链接框，所以可以放在超高级设置里实现。

**Comment by AlanDecode** [comment]
暂不考虑。
