### ISSUE TITLE
3.4.0版本新发文章无法自动添加图片信息

### ISSUE THREAD

**Issue by luhe0625** [AlanDecode/Typecho-Theme-VOID#27]
新发布文章不会自动添加信息，getimginfo 处理失败，cleanimginfo 可以清除信息。是不是对数据库权限有些要求，我是虚拟主机。
另外，图集排版自动适应宽度也不行。您的示例是这样：![](https://s2.ax1x.com/2019/10/28/K6hxOI.png)。
我的是这样：![](https://s2.ax1x.com/2019/10/28/K643p4.png)。
我的博客相册链接：https://luhe.xyz/photos.html
查看 F12 也没能理解问题出在哪里。

**Comment by AlanDecode** [comment]
关于图集，默认就是你这样的超出文本的大图集，若要与文本对齐高级设置里有对应选项。
关于获取图片信息，请提供更多信息，包括 PHP 版本，MySQL 版本，以及 getimginfo 具体输出的内容等。注意 PHP 要启用 curl 扩展。

**Comment by luhe0625** [comment]
图集原来是这样！我居然从来没想过去改成 flase ==

![](https://s2.ax1x.com/2019/10/28/K6bdr4.png)
PHP 版本 7.2.7，MySQL 版本 5.6.45，curl 已启用。
getimginfo 显示 `本次共解析 0 张图片，跳过 0 张图片。22 张图片处理失败。`

**Comment by AlanDecode** [comment]
网站是否打开了 Markdown？原文内容是怎么样的？

**Comment by luhe0625** [comment]
markdown 已打开
所有文章都没法获取信息，我换了台闲置的虚拟主机测试可以获取。
getimginfo
![](https://s2.ax1x.com/2019/10/28/K6xafs.png)
闲置主机参数
![](https://s2.ax1x.com/2019/10/28/K6xh11.png)

**Comment by AlanDecode** [comment]
请给出其中一篇文章的原文，我这边好测试。

**Comment by luhe0625** [comment]
https://luhe.xyz/archives/73/

**Comment by AlanDecode** [comment]
**原文**

**Comment by luhe0625** [comment]
前段时间关注苹果涉港应用那件事，曾将 App Store 切换到港区查看，不小心发现 App 榜首的 Shadowrocket 更新适配了 IOS13 的深色模式，当时就想着我也得把我的老客户端更新一下，我太喜欢深色模式了。

今天刚好有空，就去 [SockBoom](https://sockboom.ink/auth/register?affid=29161) 看了下，正好有美区 ID，教程里却写的另一个客户端 Quantumult，于是我就将这两个客户端都下载下来简单对比一下。

### 界面
![](https://pic-cdn.sukiu.net/2019/10/27/1.jpg)
![](https://pic-cdn.sukiu.net/2019/10/27/2.jpg)
- 首先是界面 UI 的对比，Shadowrocket 是老牌 SSR 客户端了，遵循原生 IOS 的设计风格，很讨我的喜欢，我认为工具类应用就该这么呼应系统风格，体验上没有割裂感。负一屏的小部件也是我比较喜欢的风格，可以实现一键打开代理，切换代理模式，还可以实时查看网速（不管你有没有开启代理，节省一个小部件位置）。对了，新版的小部件似乎有 BUG，需要在设置里添加常用节点，删除小部件再添加才能勉强正常使用，偶现打开开关自动跳转应用，开关还会来回横跳，等待修复。

- 相对的，Quantumult 的设计就更加前卫一些，首页一张世界地图非常具有辨识度，用来指示节点位置。首页上方显示本次连接时间和流量，这点对于我来说非常好用。首页下方中间一个圆形按钮用来切换节点和测速，这个测速的动画设计非常炫酷，测速也比 Shadowrocket 快。不管怎么说，Shadowrocket 确实要比 Shadowrocket 更加好看。另外，我觉得 Quantumult 的小部件相对而言没那么好看，不开代理的时候，下面空荡荡的。

### 功能

两者都有很多我看不懂也用不到的功能设置，主要聊下我用到的一些功能对比。
![](https://pic-cdn.sukiu.net/2019/10/27/3.jpg)
- Shadowrocket 毕竟老牌应用，支持的协议也更多，当然对于我来说，两者都是完全够用的，都支持 SockBoom 的订阅链接。另外，也都支持二维码添加节点和二维码分享节点，虽然我基本用不到。关于订阅更新，Shadowrocket 直接在首页左划就能更新，也能设置打开 APP 时自动更新，而 Quantumult 相对而言多了几个步骤，需要切换到设置里的订阅再左划更新，也没有提供自动更新的选项。
![](https://pic-cdn.sukiu.net/2019/10/27/6.jpg)
- 两者都支持全局代理，全局直连和自动分流，规则也都可自定义或者导入。一般来说两者的预设规则都是可以直接使用的，Shadowrocket 预设的规则更加丰富，配置起来也更直观一些，而 Quantumult 规则少一些。Shadowrocket 提供了规则测试，有些时候更方便一些。

- 两者都支持 iCloud 备份、下载、导入、导出配置。值得一提的是，Shadowrocket 不知道是什么原因，iCloud 备份的逻辑很令人迷惑，至今我都没完全搞懂，Quantumult 就相对而言简单一些，容易理解。
![](https://pic-cdn.sukiu.net/2019/10/27/4.jpg)
- 深色模式两者都是支持的，Shadowrocket 支持非常硬核的皮肤颜色更换，Quantumult 则提供了五种皮肤供选择。

- 节点测速上，Quantumult 要比 Shadowrocket 快太多了，应该是使用了不同的测速方案。查阅资料得知， Shadowrocket 使用了 HTTP 测速，Quantumult 则是 TCP 测速。
![](https://pic-cdn.sukiu.net/2019/10/27/5.jpg)
- 流量统计，两者都支持直连流量和代理流量查看，个人认为 Quantumult 更加直观。

- 性能上应该没有明显差距，测试同一个节点访问 P 站，打开速度差不多，没有做更具体的测速，主要应当还是看节点状况。

### 总结

经过非常粗浅的对比，我可能还是更偏爱 Shadowrocket，更加直观的界面，更加契合 IOS 的设计。而 Quantumult 还处在快速迭代期，有些 UI 设计确实更加好看，在测速上更快，只是我还不太适应这个新工具。

**Comment by AlanDecode** [comment]
这边测试是正常的，应该还是环境的原因……

**Comment by luhe0625** [comment]
有办法让 getimginfo 报错信息吗，我好去发工单。

**Comment by AlanDecode** [comment]
请先通过以下方式看看有没有报错信息

1. 注释掉插件目录/libs/ParseImg.php 中第 101 行
2. 在网站根目录 config.inc.php 中添加  `define('__TYPECHO_DEBUG__', true);`
3. 登陆后台
4. 访问 https://luhe.xyz/action/void?getsingleimginfo&cid=73

**Comment by luhe0625** [comment]
显示`Array ( [0] => 6 [1] => 0 [2] => 0 [3] => 6 ) `

**Comment by AlanDecode** [comment]
在 101 行后添加 `echo $url.'<br>';` 再重复以上步骤，看看是否已经解析出了图片链接。

**Comment by luhe0625** [comment]
![KclNEF.png](https://s2.ax1x.com/2019/10/28/KclNEF.png)

**Comment by AlanDecode** [comment]
最后一个测试在服务器上创建一个 t.php 文件，写入以下内容

```php
<?php
print_r(getimagesize('https://pic-cdn.sukiu.net/2019/10/27/1.jpg'));
```

然后在命令行中运行这个文件，或者从浏览器访问这个文件，确定 PHP 的 `getimagesize` 函数能不能正常使用。

**Comment by luhe0625** [comment]
显示空白

**Comment by AlanDecode** [comment]
所以这个函数没有正常运行。可能的问题是：

1. pic-cdn 这个域设置了防盗链，所以不允许从别的地方请求图片信息
2. PHP 的配置问题，不能用 getimagesize 这个函数
3. 主机的问题，不能访问 pic-cdn 这个域

具体请咨询你的主机提供商。

**Comment by luhe0625** [comment]
跟主机商扯皮了两天终于好了。

- 一开始让我改 php.ini，怎么改问了也不说。
- 今天凌晨 5 点突然让我重试，成功了，也没有说到底做了什么操作。

尴尬，总结就是以后一定要买大厂的服务器，虚拟主机太不靠谱了。

感谢开发者帮助我排查问题，谢谢！
