### ISSUE TITLE
safari 浏览网页时出现莫名字符

### ISSUE THREAD

**Issue by lushann** [AlanDecode/Typecho-Theme-VOID#29]
**实际行为描述**
电脑 chrome 浏览时正常, safari 浏览时出现莫名字符(iphone 和 mac都可复现)

**应有的行为**
内容应显示一致

**复现步骤**
1. Chrome 打开 https://lushan.me/archives/33/

![image](https://user-images.githubusercontent.com/24622986/68064982-aeec0500-fd5d-11e9-9fcf-f85c12a3c2dc.png)

此内容显示正常

2. safari 打开 https://lushan.me/archives/33/
![image](https://user-images.githubusercontent.com/24622986/68064988-c3c89880-fd5d-11e9-85b9-d74e3905a78a.png)

![image](https://user-images.githubusercontent.com/24622986/68064999-dfcc3a00-fd5d-11e9-8b34-702d39b9afd5.png)

出现莫名字符

**配置与环境**
* 出错页面链接：https://lushan.me/archives/33/
* PHP 版本： php 7.2
* MySQL 版本: 5.7.27-0 ubuntu0.18.04.1 (Ubuntu)
* Typecho 版本：1.1  (17.10.30)
* 主题版本： 3.4.0
* 插件版本：1.2

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
这个问题已确认是 Safari 或思源宋体本身的问题，暂无可靠的修复方法。
