### ISSUE TITLE
如果生成文章的目录

### ISSUE THREAD

**Issue by jackytsu** [AlanDecode/Typecho-Theme-VOID#31]
**问题描述**
参见[这篇文章](https://jacky.live/code-store/wsl-uses-the-road-1-to-install-centos.html)，后台编辑时已经打开了文章目录选项，文章中的标题使用的语法是：`# 内容标题`。请问目录的写法是有什么要求吗？

**配置与环境**
* 出错页面链接：https://jacky.live/code-store/wsl-uses-the-road-1-to-install-centos.html
* PHP 版本：
* MySQL 版本：
* Typecho 版本：1.2 (18.10.23)
* 主题版本：3.4.0
* 插件版本：3.4.0

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
主题只会为 2 到 6 级标题生成目录

**Comment by jackytsu** [comment]
谢谢
我把所有一级标题改为二级后就正常生成目录了。
