### ISSUE TITLE
PJAX&&Aplayer出现冲突

### ISSUE THREAD

**Issue by MiChongGET** [AlanDecode/Typecho-Theme-VOID#35]
**实际行为描述**
当开启PJAX功能的时候，同时开启 APlayer插件的时候，发现当打开包含音乐的页面时，音乐控件不显示，只有再次刷新页面才会出现控件。

**应有的行为**
两个功能互不干扰

**复现步骤**
开启PJAX功能，然后再文章中插入歌曲，访问文章，音乐控件不显示，再次刷新才会出现控件

**配置与环境**
* 出错页面链接：
* PHP 版本：php7.3.8
* MySQL 版本：mysql5.7.27
* Typecho 版本：1.2 (18.10.23)
* 主题版本：3.4.0
* 插件版本：1.2

**截图（若有）**
![image](https://user-images.githubusercontent.com/15011479/75628647-0b7d0500-5c16-11ea-8299-2fc2f93746c2.png)
插件
![image](https://user-images.githubusercontent.com/15011479/75628678-3c5d3a00-5c16-11ea-88b1-769a914439bd.png)

**Comment by AlanDecode** [comment]
https://github.com/MoePlayer/APlayer-Typecho/blob/master/README.md#faq
