### ISSUE TITLE
部分代码无法高亮显示

### ISSUE THREAD

**Issue by molun** [AlanDecode/Typecho-Theme-VOID#37]
**问题描述**
部分代码不能实现Mac 风格代码块高亮显示

**配置与环境**
* 出错页面链接：http://www.molun.cf/index.php/archives/14/
* PHP 版本：
* MySQL 版本：
* Typecho 版本：1.2 (18.10.23)
* 主题版本：3.4.0
* 插件版本：1.2

**截图（若有）**
![image](https://user-images.githubusercontent.com/23138506/77405832-b08e9600-6dee-11ea-827b-194f39777265.png)
![image](https://user-images.githubusercontent.com/23138506/77405876-c0a67580-6dee-11ea-81bc-3f45ee02a44d.png)
![image](https://user-images.githubusercontent.com/23138506/77405925-d320af00-6dee-11ea-8211-0b303a3b29eb.png)

**补充信息**

**Comment by AlanDecode** [comment]
请使用正确的 Markdown 语法标记代码块。
