### ISSUE TITLE
刚装的主题 底部 感谢陪伴 显示时间不正确

### ISSUE THREAD

**Issue by foxhound1227** [AlanDecode/Typecho-Theme-VOID#38]
刚装的主题 底部的感谢陪伴显示时间位18348 天 21 小时 18 分 0 秒
不知道这个是读取的哪里的时间？

docker内nginx下装的Typecho
MySQL 也是docker装的5.6版本

 主题版本：版本: 3.4.0
 插件版本：1.2

**Comment by AlanDecode** [comment]
依据你第一篇文章的发布时间

**Comment by foxhound1227** [comment]
我迁移了blog以后 时间就变了 变成了 18348 天 有没有什么办法解决？
