### ISSUE TITLE
关于Markdown渲染脚本

### ISSUE THREAD

**Issue by Penghaiku** [AlanDecode/Typecho-Theme-VOID#39]
**问题描述**
能否在主题中添加markdown渲染所需的js，支持甘特图，流程图，时序图等等，markdown preview enhanced中支持的那些都可以的。这样的话，可以让typecho 如虎添翼；；

**配置与环境**
任意
* 出错页面链接：
无
* PHP 版本：
* MySQL 版本：
* Typecho 版本：
* 主题版本：
最新release
* 插件版本：
最新release

**截图（若有）**

无
**补充信息**

**Comment by AlanDecode** [comment]
抱歉，目前这方面需求还不太多。后续也许会考虑。

**Comment by Penghaiku** [comment]
editorMD插件包含了这些功能，但是和主题有冲突，emmm，能否移植？

**Comment by AlanDecode** [comment]
不考虑。
