### ISSUE TITLE
目录树的一些显示问题

### ISSUE THREAD

**Issue by festoney8** [AlanDecode/Typecho-Theme-VOID#4]
- 小bug:  页面拉到底部时,  较长的目录树会覆盖footer

- bug: 目录树上方有多个欢迎的div盖住, 导致一些标签不可点击
![image](https://user-images.githubusercontent.com/36254268/52464573-603a8180-2bb6-11e9-9681-82d34a222eba.png)

- idea:  希望对目录树增加一些样式.  如 鼠标经过突出显示,  标题加粗或可折叠等

感谢大佬提供并开源漂亮的主题~

**Comment by AlanDecode** [comment]
谢谢反馈与建议，会在下一次更新时考虑。

**Comment by ZhangJun1015** [comment]
![Screen Shot 2019-03-13 at 20 45 26](https://user-images.githubusercontent.com/20275222/54280127-acbc1700-45d1-11e9-91cd-8c5dabdc77f5.png)
![Screen Shot 2019-03-13 at 20 45 22](https://user-images.githubusercontent.com/20275222/54280129-ad54ad80-45d1-11e9-9477-de4bfe38e24b.png)
启用主题之后，用模版生成归档页面，可是有个年份居然排版有问题。
在 Safari 和 Chrome 里面都显示错位。

**Comment by AlanDecode** [comment]
请附上错误页面，光是一张图看不出问题所在。

**Comment by ZhangJun1015** [comment]
> 请附上错误页面，光是一张图看不出问题所在。

http://www.sirit.com.cn/index.php/9.html

**Comment by AlanDecode** [comment]
已在 [493e5f5b](https://github.com/AlanDecode/Typecho-Theme-VOID/commit/493e5f5b250a9fadfcb7ea1cbae3af75757b7ebf) 中修复，你可以尝试开发版，发布版稍后更新。
