### ISSUE TITLE
3.5.0更新后iframe显示异常

### ISSUE THREAD

**Issue by haojie06** [AlanDecode/Typecho-Theme-VOID#42]
**实际行为描述**
在更新到3.5.0之后，使用网易云音乐的外链播放器出现异常，iframe外还有一个很大的框(3.4.0的时候是正常的)
![image](https://user-images.githubusercontent.com/32638818/80907169-11db4a80-8d47-11ea-9234-c175040c6edb.png)

**Comment by AlanDecode** [comment]
在开发版中已修复
