### ISSUE TITLE
关于蛆音娘表情无法生效。

### ISSUE THREAD

**Issue by YanLiye2003** [AlanDecode/Typecho-Theme-VOID#43]
**实际行为描述**
从3.4覆盖安装升级致3.5后，新增加的蛆音娘表情，在评论中不生效，输出仍是字串符（ 在评论中依然是:&(蛆音娘_偷看)  ）

**应有的行为**

应该输出表情呀

**复现步骤**

**配置与环境**
* 出错页面链接：例如www.okace.cn中
* PHP 版本：7.3
* MySQL 版本：5.6.46
* Typecho 版本：1.1
* 主题版本：3.5
* 插件版本：1.2

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
麻烦确认是否覆盖完整，尤其是 includes/comments.php 和 libs/contents.php 两个文件。
确认都没问题，可以尝试重启一下主题。
