### ISSUE TITLE
代码无法高亮,关闭Mac代码风格和开启Mac代码风格均无法高亮

### ISSUE THREAD

**Issue by zz1998022** [AlanDecode/Typecho-Theme-VOID#44]
## 问题描述:

默认代码无法高亮,关闭Mac代码风格后仍然无法高亮
我发现貌似是pre类名貌似没有添加上
我试着手动加上类名，但是并没有效果，应该是没有这个样式文件吧

这是博主你的代码块:
![image.png](https://i.loli.net/2020/05/21/VvWnIeLt3yMksA7.png)

这是我的代码块:
![image.png](https://i.loli.net/2020/05/21/MqQWyN2jGL3BlH6.png)

我检查过我的markdown语法，在typora上面是完全没有问题的,由于我没学过php，也不知道你用的是什么插件,所以无法自行解决,希望博主能给个解决方案,感激不尽

**Comment by AlanDecode** [comment]
请按照 issue 模板提供完整的信息。

**Comment by zz1998022** [comment]
**问题描述**

代无法高亮,无论是开启mac风格还是关闭mac风格,我发现貌似是类名没有添加上

**配置与环境**

默认配置

* 出错页面链接：http://mashiro.online/javascript_study_note/nodeUploadFile.html
* PHP 版本：7.1
* MySQL 版本：5.6
* Typecho 版本：1.1
* 主题版本：3.5.0
* 插件版本：1.2


**截图（若有）**

这是博主你的代码块:
![image.png](https://i.loli.net/2020/05/21/VvWnIeLt3yMksA7.png)

这是我的代码块:
![image.png](https://i.loli.net/2020/05/21/MqQWyN2jGL3BlH6.png)

**补充信息**

**Comment by AlanDecode** [comment]
1. 确认编辑器插件是否冲突（我没有使用任何编辑器插件）
2. 确认 Markdown 代码块语法正确：

<pre>
```python
print("Hello World")
```
</pre>

**Comment by zz1998022** [comment]
确定EditorMD和主题有冲突,禁用插件后好了,感谢解答
