### ISSUE TITLE
熊猫大大，能否加一个是否默认隐藏目录的高级配置

### ISSUE THREAD

**Issue by ShaoPak** [AlanDecode/Typecho-Theme-VOID#48]
直接显示目录有些影响美观性，能否加一个默认隐藏目录的高级配置，读者想观看目录时再手动展开就好

**Comment by monsterxcn** [comment]
如果你是自己编译的话，在 assets/VOID.js 里有一段：

```javascript
    // 解析文章目录
    parseTOC: function () {
        if ($('.TOC').length > 0) {
            // ...
            
            // 检查目录
            if(window.innerWidth >= 1200) {
                TOC.open();
            } 
        }
    },
```

将 `TOC.open()` 修改为 `TOC.close()` 可以实现默认隐藏目录。

如果是打包好的，在 assets/VOID.xxxxx.js 里搜索一下 `TOC.open` 找找。

**Comment by ShaoPak** [comment]
> 如果你是自己编译的话，在 assets/VOID.js 里有一段：
> 
> ```js
>     // 解析文章目录
>     parseTOC: function () {
>         if ($('.TOC').length > 0) {
>             // ...
>             
>             // 检查目录
>             if(window.innerWidth >= 1200) {
>                 TOC.open();
>             } 
>         }
>     },
> ```
> 
> 将 `TOC.open()` 修改为 `TOC.close()` 可以实现默认隐藏目录。
> 
> 如果是打包好的，在 assets/VOID.xxxxx.js 里搜索一下 `TOC.open` 找找。

非常感谢大佬的指导
