### ISSUE TITLE
怎么让首页背景图铺满整个监视器

### ISSUE THREAD

**Issue by 2804567299** [AlanDecode/Typecho-Theme-VOID#49]
**问题描述**
您好，我想知道怎么使首页背景图铺满整个屏幕，类似于https://9bie.org/ 这样的样式？我实在不知道怎么更改，烦请您帮忙解答

**配置与环境**
* 出错页面链接：index.php
* PHP 版本：7.0
* MySQL 版本：5.6
* Typecho 版本：1.1
* 主题版本：最新
* 插件版本：最新

**截图（若有）**
![批注 2020-07-28 100418](https://user-images.githubusercontent.com/32974089/88611292-4e56e200-d0bb-11ea-8119-ecbb42964e46.png)

![批注 2020-07-28 100601](https://user-images.githubusercontent.com/32974089/88611342-675f9300-d0bb-11ea-8c1f-e705741769f1.png)

**补充信息**

**Comment by AlanDecode** [comment]
高级设置中 `desktopBannerHeight ` 和 `mobileBannerHeight ` 选项可以设置头图高度。

**Comment by 2804567299** [comment]
可以，感谢解答
