### ISSUE TITLE
主题部署失败，求助~！

### ISSUE THREAD

**Issue by NoDreaminger** [AlanDecode/Typecho-Theme-VOID#50]
**问题描述**
部署主题失败:更改主题页面、博客对外页面500错误

**配置与环境**
* 出错页面链接：
* PHP 版本：PHP 7.2.31 (cli) (built: May 31 2020 16:18:31) ( NTS )
* MySQL 版本：5.6.47 MySQL Community Server (GPL)
* Typecho 版本：1.1 (17.10.30)
* 主题版本：3.2.0~3.5.1
* 插件版本：1.2

**截图（若有）**
![图片](https://user-images.githubusercontent.com/41988611/89010416-25e01980-d341-11ea-9085-1e92f48fe98d.png)
![图片](https://user-images.githubusercontent.com/41988611/89010524-545df480-d341-11ea-8692-a69fa385d1a5.png)

**补充信息**

我按照教程将PHP升级到最新版本，禁用了所有的插件，确保没有其他插件同时加载了JQuery。此时我应用VOID主题得到了这个错误。我尝试了3.2.0~3.5.1版本都得到这个错误。

**Comment by AlanDecode** [comment]
试试先安装启用插件，然后再启用主题。如果直接覆盖主题不行的话，可以先禁用主题，上传主题后再重新启用

**Comment by NoDreaminger** [comment]
> 
> 
> 试试先安装启用插件，然后再启用主题。如果直接覆盖主题不行的话，可以先禁用主题，上传主题后再重新启用

已成功，先感谢！

**Comment by NoDreaminger** [comment]
> 
> 
> > 试试先安装启用插件，然后再启用主题。如果直接覆盖主题不行的话，可以先禁用主题，上传主题后再重新启用
> 
> 已成功，先感谢！

在安装这个主题之前，我php版本是5.x。按照部署说明更新到7.x后，部署失败。重新安装typecho解决!
