### ISSUE TITLE
超高级设置填入参数后不起作用

### ISSUE THREAD

**Issue by zzfiu** [AlanDecode/Typecho-Theme-VOID#52]
**问题描述**
超高级设置填入参数后不起作用

**配置与环境**
* 出错页面链接：
* PHP 版本：7.4
* MySQL 版本：5.5.62
* Typecho 版本：1.2
* 主题版本：3.5.1
* 插件版本：1.2

**截图（若有）**

**补充信息**

**Comment by zzfiu** [comment]
![Snipaste_2020-08-08_23-55-41](https://user-images.githubusercontent.com/15867555/89714654-d352cd00-d9d2-11ea-9443-78bfb5bb185f.png)

**Comment by ShaoPak** [comment]
> **问题描述**
> 超高级设置填入参数后不起作用
> 
> **配置与环境**
> 
> * 出错页面链接：
> * PHP 版本：7.4
> * MySQL 版本：5.5.62
> * Typecho 版本：1.2
> * 主题版本：3.5.1
> * 插件版本：1.2
> 
> **截图（若有）**
> 
> **补充信息**

这种情况大多是格式出问题了，比如末尾的逗号等等，仔细检查一下，特别是末尾的部分

**Comment by AlanDecode** [comment]
配置需要符合 JSON 格式。

**Comment by zzfiu** [comment]
"useFiraCodeFont": true,
    "headerMode": 0,
    "desktopBannerHeight" : 70,
    "bluredLazyload": false,
    "CDNType": {
        "static.imalan.cn": "UPYUN" // UPYUN, QINIU
    },

这样写对吗

**Comment by lcnwys** [comment]
> ```
> "useFiraCodeFont": true,
> "headerMode": 0,
> "desktopBannerHeight" : 70,
> "bluredLazyload": false,
> "CDNType": {
>     "static.imalan.cn": "UPYUN" // UPYUN, QINIU
> },
> ```
> 
> 
> 这样写对吗

https://github.com/AlanDecode/Typecho-Theme-VOID/blob/master/advanceSetting.sample.json  在你的主题根目录下有一个advanceSetting.sample.json 或者直接访问上面的网址查看，选择你需要的内容，以json 格式进行填写，如果不清楚什么是json，那就百度下
