### ISSUE TITLE
建议添加站点Logo设置选项

### ISSUE THREAD

**Issue by luc-yang** [AlanDecode/Typecho-Theme-VOID#53]
如题，在设置中无法找到站点logo的选项，希望可以添加，谢谢。

**Comment by easechen** [comment]
直接在网站根目录传一个favicon.ico

**Comment by easechen** [comment]
> 如题，在设置中无法找到站点logo的选项，希望可以添加，谢谢。

直接在网站根目录传一个favicon.ico

**Comment by design-1996** [comment]
> > 如题，在设置中无法找到站点徽标的选项，希望可以添加，谢谢。
> 
> 直接在网站根目录传一个favicon.ico

我按你的方式添加了，添加了favicon.ico一样不显示徽标
