### ISSUE TITLE
3.5版本安装后网站出现500错误

### ISSUE THREAD

**Issue by caoliang12121** [AlanDecode/Typecho-Theme-VOID#54]
**实际行为描述**

**应有的行为**

**复现步骤**

**配置与环境**
* 出错页面链接：
* PHP 版本：
* MySQL 版本：
* Typecho 版本：
* 主题版本：
* 插件版本：

**截图（若有）**

**补充信息**

**Comment by raingnight** [comment]
同500错误

- mysql 5.7.32 
- php 5.4.16 
- Typecho 1.1(17.10.30)
- 主题、插件均为3.5.1包下的文件
- 错误链接：http://服务器ip/index.php/action/themes-edit?change=VOID&_=3b6afb9669fb50b9fd33bd61121f7dca

**Comment by AlanDecode** [comment]
参见常见问题。
