### ISSUE TITLE
是否可以修改每一页显示的文章数量

### ISSUE THREAD

**Issue by aoyouer** [AlanDecode/Typecho-Theme-VOID#55]
作者你好，请问是否可以修改网站中每一页显示的文章数量，因为文章较多的情况下，首页只能展示几篇文章，需要频繁的翻页，如果可以的话该怎么操作呢?

**Comment by aretlas** [comment]
同问啊，想调高每页文章数

**Comment by aoyouer** [comment]
> 同问啊，想调高每页文章数

已经解决了，这是typecho自带的设置， 设置-阅读 里面可以设置每一页的文章数量
