### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by design-1996** [AlanDecode/Typecho-Theme-VOID#56]
希望下个版本能增加，网站图标显示，以及关闭上传的图片名字选项。按照你的方法上传ico徽标文件到网站根目录，然后清除浏览器缓存还是一样不显示徽标。是不是还要更改什么代码之类的

**Comment by AlanDecode** [comment]
Typecho 会自动将上传的图片名放到 Markdown 中，该名称将作为图题使用，建议自行修改这部分信息。
