### ISSUE TITLE
启用主题后打开页面都是新窗口

### ISSUE THREAD

**Issue by LimonChoms** [AlanDecode/Typecho-Theme-VOID#58]
自带主题没问题，启用了大佬的主题后点开文章或者什么任意界面都是从新窗口打开，请问是哪里设置错了吗？

**Comment by AlanDecode** [comment]
有错误页面吗

**Comment by LimonChoms** [comment]
> 有错误页面吗

没有错误，就是强制在新窗口打开，然后琢磨了一下，发现标准443端口没问题，但是换成其他端口就强制开新窗口了，原版主题其他端口是没问题的
