### ISSUE TITLE
如何设置文章首行自动缩进

### ISSUE THREAD

**Issue by austinmarsray** [AlanDecode/Typecho-Theme-VOID#59]
**问题描述**

**配置与环境**
* 出错页面链接：
* PHP 版本：
* MySQL 版本：
* Typecho 版本：
* 主题版本：
* 插件版本：

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
目前并没有这样的设置，可自行书写 CSS，或者手动输入空格。
