### ISSUE TITLE
友链添加失败

### ISSUE THREAD

**Issue by LongStudy** [AlanDecode/Typecho-Theme-VOID#6]
友链处填写
[links]
[熊猫小A](https://www.imalan.cn)+(https://secure.gravatar.com/avatar/1741a6eef5c824899e347e4afcbaa75d?s=200&r=G&d=)
[熊猫小A的博客](https://blog.imalan.cn)+(https://secure.gravatar.com/avatar/1741a6eef5c824899e347e4afcbaa75d?s=64&r=G&d=)
[/links]
然后文章内容显示渲染后代码，无法显示图片等

**Comment by LongStudy** [comment]
忘记加!!!了，不好意思

**Comment by AlanDecode** [comment]
使用 [links] 的方式插入友链无需加 `!!!` 才对
