### ISSUE TITLE
如何修改VOID配套插件让其在sqlite数据库下可用

### ISSUE THREAD

**Issue by NOAME18** [AlanDecode/Typecho-Theme-VOID#60]
**问题描述**
开VOID配套插件v1.20出错,500页面，Database Query Error。虽然看过注意事项知道作者不打算适配mysql外的数据库，但仍希望作者或者其他大佬能提供修改和适配sqlite思路？感激不尽..

**配置与环境**
* centos7+docker(荒野无灯docker镜像)
* 出错页面链接：none
* PHP 版本：未知
* MySQL 版本：none,使用sqlite数据库
* Typecho 版本：版本 1.2 (19.05.09)
* 主题版本：3.51
* 插件版本：1.20

**截图（若有）**
none

**补充信息**
none

**Comment by AlanDecode** [comment]
为适配 MySQL 以外的数据库，需要针对数据库重写部分增删改查代码，以及为了实现字数、浏览量统计等而对原表做调整的代码（比如增加数据表列等）。
