### ISSUE TITLE
请问一下为什么图片这么大

### ISSUE THREAD

**Issue by sqjuanke** [AlanDecode/Typecho-Theme-VOID#62]
**问题描述**

**配置与环境**
* 出错页面链接：
* PHP 版本：
* MySQL 版本：
* Typecho 版本：
* 主题版本：
* 插件版本：

**截图（若有）**
![image](https://user-images.githubusercontent.com/19483695/102898314-4b162580-44a4-11eb-82d9-8ec88a3131e5.png)

**补充信息**

首先感谢作者开发出这么好主题

有个小疑问，想请教一下
为什么我在正文中的图片这么大
编写的时候是采用图集

`[photos]
![](http://192.168.2.103:5800/usr/uploads/2020/12/1901386847.jpeg#vwid=512&vhei=512)
![](http://192.168.2.103:5800/usr/uploads/2020/12/712810530.jpeg#vwid=1080&vhei=1080)
[/photos]`

**Comment by AlanDecode** [comment]
高级设置中的 largePhotoSet 选项可以用来控制这个宽度。
