### ISSUE TITLE
包含矩阵的公式无法渲染

### ISSUE THREAD

**Issue by lxalxy** [AlanDecode/Typecho-Theme-VOID#64]
**实际行为描述**
例如
$$\be­gin{pma­trix} \color{red}1 \ \color{green}2 \ \color{blue}3 \end{pma­trix} + x = \be­gin{pma­trix} \color{red}1 + x \ \color{green}2 + x \ \color{blue}3 + x \end{pma­trix}$$

<img width="688" alt="Snipaste_2021-02-10_19-33-53" src="https://user-images.githubusercontent.com/7473229/107504903-ee4b0780-6bd6-11eb-989d-660aafe6106b.png">

**应有的行为**
<img width="130" alt="Snipaste_2021-02-10_19-34-42" src="https://user-images.githubusercontent.com/7473229/107505006-0ae73f80-6bd7-11eb-84e0-37625a75dc8a.png">

**复现步骤**

**配置与环境**
* 出错页面链接：
* PHP 版本：7.4.13
* MySQL 版本：maridb 10.4.17 
* Typecho 版本：1.2
* 主题版本：3.5.1
* 插件版本：1.2

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
可能是 mathjax 不支持这个环境
