### ISSUE TITLE
归档页的弹窗

### ISSUE THREAD

**Issue by xulu199705** [AlanDecode/Typecho-Theme-VOID#65]
**实际行为描述**
访问归档页面时，有“find input author error!”弹窗。

![归档页弹窗](https://user-images.githubusercontent.com/17242727/112929900-eece3c00-914b-11eb-9bc9-8b9cb177edba.png)

* Typecho 版本：1.1 (17.10.30)
* 主题版本：3.51
* 插件版本：1.2

**Comment by AlanDecode** [comment]
VOID 的代码里没有这行报错，检查一下插件，或者你自己是否改了什么。
