### ISSUE TITLE
发布新文章耗时非常长

### ISSUE THREAD

**Issue by patricsun** [AlanDecode/Typecho-Theme-VOID#68]
**实际行为描述**

发布新文章需要等待5到十几秒才回到文章列表页面

**应有的行为**

使用其他主题都在1秒内完成发布操作

**复现步骤**

如果重复发布文章，则只有第一篇文章出现这个状况

**配置与环境**
* 出错页面链接：后台页面
* PHP 版本：7.4
* MySQL 版本：10.5.6(mariadb)
* Typecho 版本：1.2 (18.10.23)
* 主题版本：3.5.1
* 插件版本：1.2

**截图（若有）**

**补充信息**

**Comment by AlanDecode** [comment]
安装主题后第一次发布文章会在后台进行一些统计分析，之后就不会了。
