### ISSUE TITLE
footer遮盖底部弹出表情框

### ISSUE THREAD

**Issue by EHfive** [AlanDecode/Typecho-Theme-VOID#8]
![Screenshot_20190317_001036](https://user-images.githubusercontent.com/24871166/54478057-332e5e00-4849-11e9-86a1-d5ddb90a4b61.png)
原因是
.main { overflow-x: hidden; }
应该只对内部有可能水平溢出的子元素应用 overflow-x: hidden

**Comment by EHfive** [comment]
或者是计算当空间不足时向上显示

**Comment by AlanDecode** [comment]
我已注意到这个问题，感谢反馈。
