### ISSUE TITLE
点击ENJOY 按钮一直提示“投票失败 o(╥﹏╥)o”

### ISSUE THREAD

**Issue by SilkageAB** [AlanDecode/Typecho-Theme-VOID#84]
任一文章点击ENJOY 按钮一直提示“投票失败 o(╥﹏╥)o”
已知权限没有问题，后台“互动”显示“加载中”

出错页面链接：本站点任何文章界面
PHP 版本：php7.4
MySQL 版本：MySQL5.7
Typecho 版本：1.20
主题版本：3.5.1
插件版本：1.2

**Comment by biyuehu** [comment]
解决了吗
